### ISSUE TITLE
 java.lang.SecurityException: com.android.externalstorage has no access to content://media/external_primary/file/1000029734

### ISSUE THREAD

**Issue by noshair** [GauthamAsir/WhatsApp_Status_Saver#21]
This issue is coming

**Comment by GauthamAsir** [comment]
Can you elaborate the issue and mention the below details.

- Android version
- Is it Emulator
- Steps to re-produce
- Share the complete Log
- Does Permission granted

**Comment by noshair** [comment]
Yes

**Comment by noshair** [comment]
permission is granted

**Comment by noshair** [comment]
Root cause (1 of 1)
                                                                                                    java.lang.SecurityException: com.android.externalstorage has no access to content://media/external_primary/file/1000029962
                                                                                                    	at android.os.Parcel.createExceptionOrNull(Parcel.java:3023)
                                                                                                    	at android.os.Parcel.createException(Parcel.java:3007)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:2990)
                                                                                                    	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
                                                                                                    	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:153)
                                                                                                    	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:780)
                                                                                                    	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:2034)
                                                                                                    	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1849)
                                                                                                    	at android.content.ContentResolver.openInputStream(ContentResolver.java:1525)
                                                                                                    	at com.bumptech.glide.load.data.StreamLocalUriFetcher.loadResourceFromUri(StreamLocalUriFetcher.java:74)
                                                                                                    	at com.bumptech.glide.load.data.StreamLocalUriFetcher.loadResource(StreamLocalUriFetcher.java:50)
                                                                                                    	at com.bumptech.glide.load.data.StreamLocalUriFetcher.loadResource(StreamLocalUriFetcher.java:13)
                                                                                                    	at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:44)
                                                                                                    	at com.bumptech.glide.load.engine.SourceGenerator.startNextLoad(SourceGenerator.java:95)
                                                                                                    	at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:88)
                                                                                                    	at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:311)
                                                                                                    	at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:280)
                                                                                                    	at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:235)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
                                                                                                    	at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:413)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
                                                                                                    	at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultPriorityThreadFactory$1.run(GlideExecutor.java:372)

**Comment by noshair** [comment]
and image is not showing

**Comment by noshair** [comment]
It is android note 10 Lite

**Comment by noshair** [comment]
check this on android 13
